# Provides centralized, environment-agnostic configuration for all application components.
# This ConfigMap stores non-sensitive settings like Azure resource names and feature flags, which are mounted as environment variables into the pods.
apiVersion: v1
kind: ConfigMap
metadata:
  name: env-config
  namespace: finmon-app
  labels:
    project: financial-monitoring
data:
  KEY_VAULT_URI: "https://finmon-kv-0aaa81f1.vault.azure.net/"
  AZURE_CLIENT_ID: "e48d319f-dd71-4f1a-b39a-36d8a6531660"
  AZURE_TENANT_ID: "05d4d320-0989-48fb-924f-ac123d0adaed"

  CosmosDb__DatabaseName: "FinancialTransactionsDb"
  CosmosDb__ContainerName: "Transactions"
  CosmosDb__PartitionKeyPath: "/id"

  EventHubs__EventHubName: "transactions"
  EventHubs__BlobContainerName: "eh-checkpoints"

  Messaging__Provider: "eventhubs"
  
  # Anomaly Detection Configuration
  # Options: "stateless" (no Redis dependency) or "stateful" (requires Redis)
  AnomalyDetection__Mode: "stateless"
