# Provides centralized configuration for all application components.
# This ConfigMap stores common, environment-agnostic settings. Environment-specific values are patched by overlays.
apiVersion: v1
kind: ConfigMap
metadata:
  name: env-config
  namespace: finmon-app
  labels:
    project: financial-monitoring
data:
  # Anomaly Detection Configuration
  # Options: "stateless" (no Redis dependency) or "stateful" (requires Redis)
  AnomalyDetection__Mode: "stateless"
