services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.6.1
    container_name: zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    networks:
      - financial_monitoring_network

  kafka:
    image: confluentinc/cp-kafka:7.6.1
    container_name: kafka
    ports:
      - "9092:9092"
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_ADVERTISED_LISTENERS: LISTENER_INTERNAL://kafka:29092,LISTENER_EXTERNAL://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: LISTENER_INTERNAL:PLAINTEXT,LISTENER_EXTERNAL:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: LISTENER_INTERNAL
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_CREATE_TOPICS: "transactions:1:1"
    networks:
      - financial_monitoring_network

  transactionsimulator:
    container_name: transaction_simulator
    build:
    #https://stackoverflow.com/questions/65622477/what-is-context-in-docker-compose
      context: .
      dockerfile: ./src/TransactionSimulator/Dockerfile.dev
    command: dotnet watch run --project ./src/TransactionSimulator/TransactionSimulator.csproj
    volumes:
      - ./src:/source/src
    working_dir: /source
    depends_on:
      - kafka
    environment:
      DOTNET_ENVIRONMENT: "Development"
      KEY_VAULT_URI: "${KEY_VAULT_URI}"
      AZURE_CLIENT_ID: "${AZURE_CLIENT_ID}"
      AZURE_CLIENT_SECRET: "${AZURE_CLIENT_SECRET}"
      AZURE_TENANT_ID: "${AZURE_TENANT_ID}"
      APPLICATIONINSIGHTS_CONNECTION_STRING: "InstrumentationKey=00000000-0000-0000-0000-000000000000;IngestionEndpoint=https://localhost/;LiveEndpoint=https://localhost/"
      KAFKA_BOOTSTRAP_SERVERS: "${KAFKA_BOOTSTRAP_SERVERS}"
      EventHubs__EventHubName: "${EVENTHUBS_EVENTHUB_NAME}"
      EventHubs__BlobContainerName: "${EVENTHUBS_BLOB_CONTAINER_NAME}"
      Messaging__Provider: "${MESSAGE_PROVIDER}"
      #Needed when using hot reload in docker
      #https://learn.microsoft.com/en-us/aspnet/core/tutorials/dotnet-watch?view=aspnetcore-8.0
      DOTNET_USE_POLLING_FILE_WATCHER: "true"
    networks:
      - financial_monitoring_network
    stdin_open: true
    tty: true

  transactionprocessor:
    container_name: transaction_processor
    build:
    #https://stackoverflow.com/questions/65622477/what-is-context-in-docker-compose
      context: .
      dockerfile: ./src/TransactionProcessor/Dockerfile.dev
    command: dotnet watch run --project ./src/TransactionProcessor/TransactionProcessor.csproj
    volumes:
      - ./src:/source/src
    working_dir: /source
    depends_on:
      kafka:
        condition: service_started
      mongodb:
        condition: service_healthy
    environment:
      DOTNET_ENVIRONMENT: "Development"
      KEY_VAULT_URI: "${KEY_VAULT_URI}"
      AZURE_CLIENT_ID: "${AZURE_CLIENT_ID}"
      AZURE_CLIENT_SECRET: "${AZURE_CLIENT_SECRET}"
      AZURE_TENANT_ID: "${AZURE_TENANT_ID}"
      MongoDb__ConnectionString: "mongodb://admin:password123@mongodb:27017"
      MongoDb__DatabaseName: "FinancialMonitoring"
      MongoDb__CollectionName: "transactions"
      EventHubs__EventHubName: "${EVENTHUBS_EVENTHUB_NAME}"
      EventHubs__BlobContainerName: "${EVENTHUBS_BLOB_CONTAINER_NAME}"
      Messaging__Provider: "${MESSAGE_PROVIDER}"
      AnomalyDetection__Mode: "stateless"
      #Needed when using hot reload in docker
      #https://learn.microsoft.com/en-us/aspnet/core/tutorials/dotnet-watch?view=aspnetcore-8.0
      DOTNET_USE_POLLING_FILE_WATCHER: "true"
    networks:
      - financial_monitoring_network
    stdin_open: true
    tty: true

  # MongoDB for local development - much faster than Cosmos emulator
  mongodb:
    container_name: mongodb
    image: mongo:7.0
    ports:
      - "${MONGODB_PORT:-27017}:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password123
      MONGO_INITDB_DATABASE: FinancialMonitoring
    volumes:
      - mongodb_data:/data/db
    networks:
      - financial_monitoring_network
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

  financialmonitoring-api:
    container_name: financialmonitoring_api
    build:
      context: .
      dockerfile: ./src/FinancialMonitoring.Api/Dockerfile.dev
    command: dotnet watch run --no-launch-profile
    ports:
      - "${API_PORT:-5100}:8080"
      # - "7100:8081" # HTTPS
    volumes:
      - ./src:/source/src
    working_dir: /source/src/FinancialMonitoring.Api
    environment:
      DOTNET_ENVIRONMENT: "Development"
      KEY_VAULT_URI: "${KEY_VAULT_URI}"
      AZURE_CLIENT_ID: "${AZURE_CLIENT_ID}"
      AZURE_CLIENT_SECRET: "${AZURE_CLIENT_SECRET}"
      AZURE_TENANT_ID: "${AZURE_TENANT_ID}"
      APPLICATIONINSIGHTS_CONNECTION_STRING: "InstrumentationKey=00000000-0000-0000-0000-000000000000;IngestionEndpoint=https://localhost/;LiveEndpoint=https://localhost/"
      ApiSettings__ApiKey: "${API_KEY}"
      MongoDb__ConnectionString: "mongodb://admin:password123@mongodb:27017"
      MongoDb__DatabaseName: "FinancialMonitoring"
      MongoDb__CollectionName: "transactions"
      # Port configuration environment variables
      API_PORT: "${API_PORT}"
      BLAZOR_HTTP_PORT: "${BLAZOR_HTTP_PORT}"
      BLAZOR_HTTPS_PORT: "${BLAZOR_HTTPS_PORT}"
      MONGODB_PORT: "${MONGODB_PORT}"
      # ASPNETCORE_URLS: "http://+:8080;https://+:8081"
      ASPNETCORE_URLS: "http://+:8080"
      DOTNET_USE_POLLING_FILE_WATCHER: "true"
    depends_on:
      mongodb:
        condition: service_healthy # API depends on the database being ready
    networks:
      - financial_monitoring_network


networks:
  financial_monitoring_network:
    driver: bridge

volumes:
  mongodb_data: {}
