#!/bin/bash
set -e

YELLOW='\033[1;33m'
GREEN='\033[0;32m'
CYAN='\033[0;36m'
NC='\033[0m' # No Color

echo -e "${YELLOW}======================================================${NC}"
echo -e "${YELLOW}           Application Secrets Setup Script           ${NC}"
echo -e "${YELLOW}======================================================${NC}"
echo ""
echo "This script will populate Azure Key Vault with the necessary secrets"
echo "and generate a '.env' file for your runtime configuration."
echo ""
echo -e "${YELLOW}Prerequisites:${NC}"
echo "1. You must be logged into Azure as a user with permissions to set Key Vault secrets."
echo "2. You must have already run 'terraform apply' successfully."
echo ""

read -p "Do you want to continue? (yes/no): " confirm
if [[ $confirm != "yes" ]]; then
    echo "Operation cancelled by user."
    exit 1
fi

echo -e "\n${YELLOW}--- Step 1: Verifying Prerequisites & Loading Config ---${NC}"
SECRETS_ENV_FILE=".env"
if [ ! -f "$SECRETS_ENV_FILE" ]; then
    echo -e "${YELLOW}Error: Configuration file '${SECRETS_ENV_FILE}' not found.${NC}" >&2
    exit 1
fi
source "./${SECRETS_ENV_FILE}"
echo -e "${GREEN}✓ Successfully loaded static config from '${SECRETS_ENV_FILE}'.${NC}"

if ! az account show >/dev/null 2>&1; then
    echo "ERROR: Not logged into Azure. Please run 'az login' first." >&2
    exit 1
fi
echo "Running script as Azure user: $(az account show --query "user.name" -o tsv)"

echo -e "\n${YELLOW}--- Step 2: Fetching Live Infrastructure Details from Terraform ---${NC}"
cd ./infra
KV_NAME=$(terraform output -raw key_vault_name)
KV_URI=$(terraform output -raw key_vault_uri)
AI_CS=$(terraform output -raw application_insights_connection_string)
COSMOS_URI=$(terraform output -raw cosmosdb_endpoint)
COSMOS_KEY=$(terraform output -raw cosmosdb_primary_key)
EH_CS=$(terraform output -raw eventhubs_namespace_connection_string)
EH_STORAGE_CS=$(terraform output -raw eventhub_checkpoint_storage_connection_string)
APP_IDENTITY_CLIENT_ID=$(terraform output -raw app_managed_identity_client_id)
REDIS_AZ=$(terraform output -raw redis_connection_string)
cd ..
echo -e "${GREEN}✓ Successfully retrieved infrastructure details from Terraform state.${NC}"

echo -e "\n${YELLOW}--- Step 3: Populating Secrets in Azure Key Vault ---${NC}"
az keyvault secret set --vault-name "$KV_NAME" --name "ApplicationInsights--ConnectionString" --value "$AI_CS" --output none
az keyvault secret set --vault-name "$KV_NAME" --name "CosmosDb--EndpointUri" --value "$COSMOS_URI" --output none
az keyvault secret set --vault-name "$KV_NAME" --name "CosmosDb--PrimaryKey" --value "$COSMOS_KEY" --output none
az keyvault secret set --vault-name "$KV_NAME" --name "EventHubs--ConnectionString" --value "$EH_CS" --output none
az keyvault secret set --vault-name "$KV_NAME" --name "EventHubs--BlobStorageConnectionString" --value "$EH_STORAGE_CS" --output none
az keyvault secret set --vault-name "$KV_NAME" --name "ApiSettings--ApiKey" --value "$API_KEY" --output none
az keyvault secret set --vault-name "$KV_NAME" --name "Redis--ConnectionString" --value "$REDIS_AZ" --output none
echo -e "${GREEN}✓ All application secrets have been set in Key Vault '${KV_NAME}'.${NC}"

PROJECT_ENV_FILE=".env"
echo -e "\n${YELLOW}--- Step 4: Creating/Updating '${PROJECT_ENV_FILE}' for Docker Compose ---${NC}"
cat >>"${PROJECT_ENV_FILE}" <<EOF
# This file was auto-generated by the setup_app_config.sh script.
# This file SHOULD be in .gitignore

KEY_VAULT_URI="${KV_URI}"

AZURE_CLIENT_ID="${APP_IDENTITY_CLIENT_ID}"
EOF
echo -e "${GREEN}✓ '${PROJECT_ENV_FILE}' created/updated successfully for Workload Identity.${NC}"

echo -e "\n${YELLOW}============================================${NC}"
echo -e "${YELLOW}      Application Configuration Complete!     ${NC}"
echo -e "${YELLOW}============================================${NC}"
echo ""
echo "You are now ready to run your application."
echo "The '.env' file has been populated with the necessary configuration for Workload Identity."
echo ""
echo -e "${CYAN}Next Step: Deploy Your Application:${NC}"
echo "Your Kubernetes manifests have already been updated for Workload Identity."
echo "Simply run your CI/CD pipeline by pushing to your main branch, or apply the manifests manually:"
echo -e "Run: ${GREEN}cd k8s-manifests && kubectl apply -k .${NC}"
echo ""
