FROM mcr.microsoft.com/dotnet/sdk:8.0

#Same name as docker compose
WORKDIR /source

#Imitate dir structure with src dir and dir names
COPY FinancialMonitoringSolution.sln .
COPY src/TransactionProcessor/TransactionProcessor.csproj ./src/TransactionProcessor/
COPY src/FinancialMonitoring.Models/FinancialMonitoring.Models.csproj ./src/FinancialMonitoring.Models/

RUN dotnet restore ./src/TransactionProcessor/TransactionProcessor.csproj

COPY ./src/TransactionProcessor/ ./src/TransactionProcessor/
COPY ./src/FinancialMonitoring.Models/ ./src/FinancialMonitoring.Models/

#Use this file to run commands
WORKDIR /source/src/TransactionProcessor

CMD ["dotnet", "run"]
