FROM mcr.microsoft.com/dotnet/sdk:8.0

WORKDIR /app

COPY TransactionProcessor.csproj .
RUN dotnet restore TransactionProcessor.csproj

COPY . .

CMD ["dotnet", "run", "--project", "./TransactionProcessor.csproj"]
