apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: finmon-app

resources:
- ../../base

commonLabels:
  project: financial-monitoring
  environment: local

# Remove cloud-specific resources
patchesStrategicMerge:
- remove-cloud-resources.yaml