# Local development ConfigMap patch for k3d cluster
apiVersion: v1
kind: ConfigMap
metadata:
  name: env-config
  namespace: finmon-app
data:
  Messaging__Provider: "kafka"

  Kafka__BootstrapServers: "192.168.5.54:9092"
  Kafka__GroupId: "transaction-processor-group"
  Kafka__TopicName: "transactions"

  MongoDb__ConnectionString: "mongodb://192.168.5.54:27017"
  MongoDb__DatabaseName: "FinancialTransactionsDb"
  MongoDb__CollectionName: "transactions"

  DOTNET_ENVIRONMENT: "Development"
