# Local MongoDB secrets for development environment
apiVersion: v1
kind: Secret
metadata:
  name: mongodb-secret
  namespace: finmon-app
  labels:
    project: financial-monitoring
    environment: local
type: Opaque
stringData:
  MongoDb--ConnectionString: "mongodb://localhost:27017"
  MongoDb--DatabaseName: "FinancialTransactionsDb"
  MongoDb--CollectionName: "transactions"
