# Patches to use local images instead of Azure Container Registry
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-deployment
  namespace: finmon-app
spec:
  template:
    spec:
      containers:
      - name: api
        image: financialmonitoring-api:latest
        imagePullPolicy: Never
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: processor-deployment
  namespace: finmon-app
spec:
  template:
    spec:
      containers:
      - name: processor
        image: transactionprocessor:latest
        imagePullPolicy: Never
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: simulator-deployment
  namespace: finmon-app
spec:
  template:
    spec:
      containers:
      - name: simulator
        image: transactionsimulator:latest
        imagePullPolicy: Never