apiVersion: apps/v1
kind: Deployment
metadata:
  name: processor-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: transaction-processor
  template:
    metadata:
      labels:
        app: transaction-processor
    spec:
      containers:
      - name: processor
        image: finmonacrd86a5e25.azurecr.io/transactionprocessor:latest
        envFrom:
        - secretRef:
            name: app-secrets
        - configMapRef:
            name: env-config
