apiVersion: apps/v1
kind: Deployment
metadata:
  name: processor-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: transaction-processor
  template:
    metadata:
      labels:
        app: transaction-processor
    spec:
      containers:
      - name: processor
        image: finmonacrfcea527d.azurecr.io/transactionprocessor:5795ea6a53e15bf956dc455ea4a0ae9f2112ba61
        envFrom:
        - secretRef:
            name: app-secrets
        - configMapRef:
            name: env-config
