apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: financial-api
  template:
    metadata:
      labels:
        app: financial-api
    spec:
      containers:
      - name: api
        image: finmonacrd86a5e25.azurecr.io/financialmonitoring-api:latest
        ports:
        - containerPort: 8080
        envFrom:
        - secretRef:
            name: app-secrets
        - configMapRef:
            name: env-config

---

apiVersion: v1
kind: Service
metadata:
  name: api-service
  namespace: finmon-app
spec:
  type: LoadBalancer
  selector:
    app: financial-api
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
