apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: financial-api
  template:
    metadata:
      labels:
        app: financial-api
        azure.workload.identity/use: "true"
    spec:
      serviceAccountName: finmon-app-sa
      containers:
      - name: api
        image: finmonacr0aaa81f1.azurecr.io/financialmonitoring-api:latest
        ports:
        - containerPort: 8080
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8080
          initialDelaySeconds:
          periodSeconds: 20
        readinessProbe:
          httpGet:
            path: /healthz
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 10
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "500m"
            memory: "256Mi"
        envFrom:
        - configMapRef:
            name: env-config

---

apiVersion: v1
kind: Service
metadata:
  name: api-service
  namespace: finmon-app
spec:
  type: LoadBalancer
  selector:
    app: financial-api
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
