apiVersion: apps/v1
kind: Deployment
metadata:
  name: simulator-deployment
  namespace: finmon-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: transaction-simulator
  template:
    metadata:
      labels:
        app: transaction-simulator
    spec:
      containers:
      - name: simulator
        image: finmonacrd86a5e25.azurecr.io/transactionsimulator:latest
        envFrom:
        - secretRef:
            name: app-secrets
        - configMapRef:
            name: env-config
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "500m"
            memory: "256Mi"
