apiVersion: apps/v1
kind: Deployment
metadata:
  name: simulator-deployment
  namespace: finmon-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: transaction-simulator
  template:
    metadata:
      labels:
        app: transaction-simulator
    spec:
      containers:
      - name: simulator
        image: finmonacrd86a5e25.azurecr.io/transactionsimulator:latest
        livenessProbe:
          exec:
            # This command checks if the /tmp/healthy file has been modified in the last minute.
            command:
            - find
            - /tmp/healthy
            - -mmin
            - "-1"
          initialDelaySeconds: 60
          periodSeconds: 30
        envFrom:
        - secretRef:
            name: app-secrets
        - configMapRef:
            name: env-config
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "500m"
            memory: "256Mi"
