apiVersion: v1
kind: ConfigMap
metadata:
  name: env-config
data:
  CosmosDb__DatabaseName: "FinancialTransactionsDb"
  CosmosDb__ContainerName: "Transactions"
  CosmosDb__PartitionKeyPath: "/id"

  EventHubs__EventHubName: "transactions"
  EventHubs__BlobContainerName: "eh-checkpoints"

  Messaging__Provider: "eventhubs"
