# Configures the Horizontal Pod Autoscaler (HPA) for the API Deployment.
# This automatically scales the number of API pods up or down based on CPU utilization, ensuring performance and cost-efficiency.
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: api-hpa
  namespace: finmon-app
  labels:
    project: financial-monitoring
    environment: development
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: api-deployment
  minReplicas: 1
  maxReplicas: 3
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 80
