# Defines the Kustomization for the application, bundling all related Kubernetes manifests into a single, manageable package.
# This file specifies the resources to be deployed and applies common labels to all of them.
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: finmon-app

resources:
- 00-serviceaccount.yml
- 01-namespace.yml
- 02-processor-deployment.yml
- 04-simulator-deployment.yml
- 03-api-deployment-service.yml
- 06-env-configmap.yml
- 07-api-hpa.yml
- 08-cluster-issuer.yml
- 09-api-ingress.yml

commonLabels:
  project: financial-monitoring
  environment: development
